rubygame/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root :to => 'summoner#index'
  
  get 'users/new'
  get 'users/show'

  get 'auth/index'
  get 'auth/create'
  post 'auth/index'

  get 'summoner/index'
  get 'summoner/search' => 'summoner#search'
  get 'summoner/:ign' => 'summoner#show', as: 'summoner_show'
  get 'summoner/favorites/index' => 'summoner#favoritesIndex', as: 'summoner_favorites_index'
  post 'summoner/favorites/:ign' => 'summoner#favoritesSave', as: 'summoner_favorites_save'
  delete 'summoner/favorites/:ign' => 'summoner#favoritesDelete', as: 'summoner_favorites_delete'
  
  get 'auth/:provider/callback', to: 'sessions#google_create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#google_destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  
  

end

rubygame/app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

rubygame/app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
          user.provider = auth.provider
          user.uid = auth.uid
          user.name = auth.info.name
          user.oauth_token = auth.credentials.token
          user.oauth_expires_at = Time.at(auth.credentials.expires_at)
          user.save!
        end
    end
    
    attr_accessor :password
    #attr_accessible :email, :password, :password_confirmation
    has_secure_password(validations: false)
    before_save :encrypt_password
    
    validates_confirmation_of :password
    #validates_presence_of :password, :on => :create
    #validates_presence_of :email
    #validates_uniqueness_of :email 

    #validates :email, presence:true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }, uniqueness:true
    #validates :password, presence:true, length:{within:1..32}, confirmation:true
    
    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
          user
        else
          nil
        end
    end
    
    def encrypt_password
        if password.present?
          self.password_salt = BCrypt::Engine.generate_salt
          self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end
    
end

rubygame/app/controllers/application_controller.rb
require 'rito_api'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  include SessionsHelper
  
  @@client = RitoApi::Client.new(ENV['league_api_key'], 'na', true, 180)

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  private
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

rubygame/app/controllers/auth_controller.rb
class AuthController < ApplicationController



  
  
end

rubygame/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  
  def google_create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to users_show_path
  
  end

  def google_destroy
    session[:user_id] = nil
    redirect_to auth_index_path
  end
  
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "You are successfully logged in!"
    else
      redirect_to auth_index_path, :notice => "Invalid email or password"
    end
  end
  
  

  def destroy
    log_out
    redirect_to auth_index_path, :notice => "You are successfully Logged out!"
  end
  
end

rubygame/app/controllers/summoner_controller.rb
class SummonerController < ApplicationController
 
  def index
    @client = @@client
    challenger = @client.challenger.solo_queue(5)
    @challengerinfo = []
    challenger.each {|x| @challengerinfo.push(@client.summoner.find(x[:playerOrTeamName]))}
  end

  def search
     if params[:search]
        # Searched from header
        @searchedSummoner = params[:search]
     else
        # Searched from landing page
        @searchedSummoner = params[:searchFrHome]
     end

     if @searchedSummoner == ''
        flash[:notice] = "Please enter a summoner name"
        redirect_to root_path
     else
        summoner = @@client.summoner.find(@searchedSummoner)

        if summoner[:status] != nil
           flash[:notice] = "Summoner does not exist"
           redirect_to root_path
        else
           redirect_to summoner_show_path(@searchedSummoner)
        end
     end
  end

  def show
      @client = @@client
      @summonerIGN = params[:ign]

      if !current_user.blank?
        favoriteCheck = Favorite.where(:user => current_user.id, :summoner => @summonerIGN).pluck(:summoner)
        if favoriteCheck != []
            @favorite = true
        end
      end
  end

  def favoritesIndex
    @client = @@client
    favoriteSummoners = Favorite.where(:user => current_user.id).pluck(:summoner)
    @summonerInfo = []
    favoriteSummoners.each { |x|
        @summonerInfo.push(@client.summoner.find(x))
        }
  end

  def favoritesSave
    summoner = params[:ign]
    if current_user.blank?
        flash[:notice] = "Please log in to add summoner #{summoner} into Favorites"
        redirect_to summoner_show_path(summoner)
    else
        user = current_user.id

        if Favorite.where(:user => current_user.id, :summoner => summoner).pluck(:summoner) == []
            Favorite.create!(:user => user, :summoner => summoner)
            Rails.cache.delete("summoner-show-page/#{summoner}")
            flash[:notice] = "Successfully added summoner #{summoner} into Favorites"
            redirect_to summoner_show_path(:ign => summoner)

        else
            flash[:notice] = "Summoner #{summoner} is already in Favorites"
            redirect_to summoner_show_path(:ign => summoner)
        end
    end
  end

  def favoritesDelete
     summoner = params[:ign]
     expire_fragment("summoner-show-page/#{summoner}")

     if current_user.blank?
        flash[:notice] = "Please log in to remove summoner from Favorites"
        redirect_to summoner_show_path(@summoner)
     else
        @unfavoriteSummoner = Favorite.where(:user => current_user.id, :summoner => summoner)
        @unfavoriteSummoner.destroy_all
        Rails.cache.delete(params[:page])
        flash[:notice] = "Successfully removed summoner #{summoner} from Favorites"
        redirect_to summoner_show_path(:ign => summoner)
     end
  end

end

rubygame/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        params.permit!
        @user = User.new(params[:user])
        @email = params[:user][:email]
        @password = params[:user][:password]
        @password_confirmation = params[:user][:password_confirmation]
        if  @email == "" or @password == "" or @password_confirmation == ""
            redirect_to users_new_path, :notice => "Fill in the Email, Password, and Password Confirmation!"
        elsif @user.save
            redirect_to auth_index_path, :notice => "Signed up!"
        end
    end
  
    def show
        @user ||= User.find(session[:user_id]) if session[:user_id]
        rescue ActiveRecord::RecordNotFound
    end
    
    def update
    end
    
    def destroy
    end
    
    helper_method :current_user
    
    #skip_before_filter :require_login
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        rescue ActiveRecord::RecordNotFound
    end
    
    #before_filter :require_user
    
    #def require_user
        #redirect_to users_path unless current_user
    #end
end

rubygame/app/helpers/application_helper.rb
module ApplicationHelper
end

rubygame/app/helpers/auth_helper.rb
module AuthHelper
end

rubygame/app/helpers/home_helper.rb
module HomeHelper
end

rubygame/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

rubygame/app/helpers/summoner_helper.rb
module SummonerHelper
end

rubygame/app/helpers/users_helper.rb
module UsersHelper
end

rubygame/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html, charset=UTF-8, width=device-width", "http-equiv" => "Content-Type", :name => "viewport", :initial-scale => "1.0"}/
    %title Ruby.gg

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %link(rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons")
    %link(rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-amber.min.css")

    %script(type="text/javascript" src="https://code.getmdl.io/1.3.0/material.min.js")

  %body
    %div{:class => "mdl-layout mdl-js-layout mdl-layout--fixed-header"}

      -# Header
      %header{:class => "mdl-layout__header"}
        %div{:class => "mdl-layout__header-row"}
          -#spacer to push rest to the right
          %div{:class => "mdl-layout-spacer"}

          %div{:class => "app-logo"}
            %img{:src => asset_path("rubygg-logo-white.svg")}/
            = link_to "ruby.gg", root_path, :class => "app-name"

          -#start search form
          - unless current_page?(root_path)
            -# Search a summoner
            = form_tag(summoner_search_path, :method => "get", id: "search-form") do
              %div{:class => "mdl-textfield mdl-js-textfield mdl-textfield--expandable custom-search-header"}
                %label{:class => "mdl-button mdl-js-button mdl-button--icon", :for => "search-expandable"}
                  %i{:class => "material-icons"} search
                %div{:class => "mdl-textfield__expandable-holder"}
                  = text_field_tag :search, '', :class => 'mdl-textfield__input', :id => 'search-expandable'
                  %label{:class => "mdl-textfield__label", :for => "search-summoner"} Search for a summoner
                = submit_tag 'find summoner', :style => "visibility: hidden; position: absolute"

      -#Menu
      %div{:class => "mdl-layout__drawer"}
        %span{:class => "mdl-layout-title"} Ruby.gg
        %nav{:class => "mdl-navigation"}
          = link_to "Home", root_path, :class => "mdl-navigation__link"
          - if current_user
            = link_to "Favorites", summoner_favorites_index_path, :class => "mdl-navigation__link"
            = link_to "Sign out", signout_path, :class => "mdl-navigation__link"
          - else
            = link_to "Log in", auth_index_path, :class => "mdl-navigation__link"

      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      -# Main
      %main{:class => "mdl-layout__content"}
        %div{:class => "page-content"}
          = yield

rubygame/app/views/partials/_summoner_card.html.haml
- ign = x[:name]
- level = x[:summonerLevel]
- icon = @client.summoner.icon(x[:profileIconId])
- rankInfo = @client.summoner.solo(x[:name])
- if rankInfo != {}
  - tier = rankInfo[:tier]
  - rank = rankInfo[:rank]
  - lp = rankInfo[:leaguePoints]
  - win = rankInfo[:wins]
  - loss = rankInfo[:losses]
  - total = win + loss
  - win_rate = (win.to_f/total) * 100
  - ranks = @client.summoner.rank_info(ign)
- else
  - tier = 'UNRANKED'
  - rank = ''
  - lp = '-'
  - win = 0
  - loss = 0
  - total = win + loss
  - win_rate = (win.to_f/total) * 100
- lp = rankInfo[:leaguePoints]
- champion_mastery = @client.summoner.champion_mastery(x[:name], 3)

%a{:class => "summoner-card", :href => "/summoner/#{ign}"}
  %div{:class => "summoner-icon-container"}
    - if tier != 'UNRANKED'
      %img{:src => asset_path("ranks-borders/#{tier}.png")}/
    %div{:class => "summoner-icon", :style => "background-image: url('#{icon}')"}

  %div{:class => "group"}
    %p{:class => "summoner-name"} #{ign}
    %p{:class => "summoner-level"} LVL : #{level}

  %div{:class => "group"}
    %p{:class => "summoner-rank"} #{tier} #{rank}
    %p{:class => "summoner-lp"} #{lp} LP
    %div{:class => "summoner-win-loss"}
      %p{:class => "summoner-win-count", :style => "width: #{win_rate}%"} #{win}W
      %p{:class => "summoner-loss-count", :style => "width: calc(100% - #{win_rate}%)"} #{loss}L

  %div{:class => "group--champions"}
    -champion_mastery.each do |x|
      - champIcon = @client.champion.icon(@client.champion.get_name(x[:championId]))
      - champLevel = x[:championLevel]
      - champMastery = @client.champion.points(x[:championPoints])
      -# For each loop here
      %div{:class => "summoner-mastery-champion"}
        %p{:class => "summoner-mastery-champion-level"} #{champLevel}
        %div{:class => "summoner-mastery-champion-icon", :style => "background-image: url('#{champIcon}')"}
        %p{:class => "summoner-mastery-champion-points"} #{champMastery}

rubygame/app/views/partials/_summoner_games.html.haml
- cache "#{m[:gameId]}", expires_in: 3.day do
  - matchdata = @client.match.get_match(m[:gameId], 0)
  - playerStats = @client.match.player_stats(m[:gameId], m[:champion], 0)
  - gameDate = Time.at(matchdata[:gameCreation]/1000).strftime("%B %e, %Y")
  - gameLength = matchdata[:gameDuration]/60.round()
  - gameType = matchdata[:queueId]
  - if matchdata[:queueId] == 420
    - gameType = 'RANKED SOLO'
  - elsif matchdata[:queueId] == 400
    - gameType = 'NORMAL'
  - elsif matchdata[:queueId] == 440
    - gameType = 'RANKED FLEX'
  - elsif matchdata[:queueId] == 450
    - gameType = 'HOWLING ABYSS'
  - elsif matchdata[:queueId] == 460
    - gameType = 'TWISTED TREELINE'
  - elsif matchdata[:queueId] == 470
    - gameType = 'RANKED TWISTED TREELINE'
  - else
    - gameType = 'CUSTOM'
  
  - gameStatus = playerStats[:stats][:win]
  
  - if gameStatus == false
    - gameStatus = 'defeat'
  - else
    - gameStatus = 'victory'
  
  - gameChampion = @client.champion.get_name(m[:champion])
  - gameChampionIcon = @client.champion.icon(gameChampion)
  - gameLevel = playerStats[:stats][:champLevel]
  - gameKills = playerStats[:stats][:kills]
  - gameDeaths = playerStats[:stats][:deaths]
  - gameAssists = playerStats[:stats][:assists]
  - gameKDAPercent = 35
  - if gameDeaths == 0
    - gameKDA = 'Perfect KDA'
  - else
    - gameKDA = "#{(gameKills.to_f + gameAssists.to_f/gameDeaths.to_f).round(2)}:1"
  - gameCS = playerStats[:stats][:totalMinionsKilled]
  - gameGold = playerStats[:stats][:goldEarned]
  - gameSummoner1 = @client.item.spells_icon(playerStats[:spell1Id])
  - gameSummoner2 = @client.item.spells_icon(playerStats[:spell2Id])
  - gameRunes = @client.match.get_runes(m[:gameId], m[:champion], 0)
  - items = []
  - (0...7).each do |x|
    -items.push(@client.item.get_icon(playerStats[:stats]["item#{x}".to_sym]))
  - stats = @client.match.stats(m[:gameId], 0)
  
  %div{:class => "recent-game-card--#{gameStatus}"}
    %div{:class => "group--game-information"}
      %p{:class => "game-type"} #{gameType}
      %p{:class => ""} #{gameStatus}
      %p{:class => ""} #{gameDate}
      %p{:class => ""} #{gameLength} Minutes
  
    %div{:class => "group--icon"}
      %p{:class => "champion"} #{gameChampion}
      %div{:class => "icon--circle", :style => "background-image: url('#{gameChampionIcon}')"}
      %p{:class => "level"} #{gameLevel}
  
    %div{:class => "group--keystones"}
      %div{:class => "group--subgroup"}
        %div{:class => "icon--smaller", :style => "background-image: url('#{gameSummoner1}')"}
        %div{:class => "icon--smaller", :style => "background-image: url('#{gameSummoner2}')"}
      %div{:class => "group--subgroup"}
        %div{:class => "icon--smaller keystone-1", :style => "background-image: url('#{gameRunes[0]}')"}
        %div{:class => "icon--smaller keystone-2", :style => "background-image: url('#{gameRunes[1]}')"}
  
    %div{:class => "group--stats"}
      %p{:class => "game-scores"} #{gameKills}/#{gameDeaths}/#{gameAssists}
      %p{:class => "game-kda"} #{gameKDA} KDA (#{gameKDAPercent}%)
      %p{:class => "game-cs-gold"} #{gameCS} CS #{gameGold} G
  
    %div{:class => "group--items"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[0]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[1]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[2]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[6]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[3]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[4]}')"}
      %div{:class => "icon--item", :style => "background-image: url('#{items[5]}')"}
  
    %div{:class => "group--summoners"}
      %div{:class => "group--subgroup"}
        - (0...5).each do |x|
          - champion100 = @client.champion.icon(@client.champion.get_name(stats[x][:championId]))
          - userName100 = @client.match.player_identities(m[:gameId], stats[x][:participantId])[:player][:summonerName]
          %div{:class => "other-summoner"}
            %div{:class => "icon--other-summoners", :style => "background-image: url('#{champion100}')"}
            %p #{userName100}
  
  
      %div{:class => "group--subgroup"}
        -(5...10).each do |x|
          - champion200 = @client.champion.icon(@client.champion.get_name(stats[x][:championId]))
          - userName200 = @client.match.player_identities(m[:gameId], stats[x][:participantId])[:player][:summonerName]
          %div{:class => "other-summoner"}
            %div{:class => "icon--other-summoners", :style => "background-image: url('#{champion200}')"}
            %p #{userName200}

rubygame/app/views/summoner/favoritesIndex.html.haml
%div{:class => "mdl-grid content-center"}
  %h3{:class => "full-width"} Favorite Summoners

  -@summonerInfo.each do |x|
    // following link intended for cucumber tests
    = link_to "Show summoner #{x[:name]}", summoner_show_path(x[:name]), :style => "visibility: hidden; position: absolute"

    = render :partial => 'partials/summoner_card', :locals => { :x => x }

rubygame/app/views/summoner/index.html.haml
- cache 'summonerIndex', expires_in: 1.day do
  %div{:class => "mdl-grid content-center"}
    -# Search a summoner
    %div{:class => "group"}
      = form_tag(summoner_search_path, :method => "get", id: "search-form") do
        %div{:class => "mdl-textfield mdl-js-textfield center-textfield"}
          = text_field_tag :searchFrHome, '', :class => 'mdl-textfield__input'
          %label{:class => "mdl-textfield__label", :for => "search-summoner"}
            %i{:class => "material-icons"} search
            %span Search for a summoner
          = submit_tag 'find summoner', :style => "visibility: hidden; position: absolute"

    -@challengerinfo.each do |x|
      // following link intended for cucumber tests
      = link_to "Show summoner #{x[:name]}", summoner_show_path(x[:name]), :style => "visibility: hidden; position: absolute"

      = render :partial => 'partials/summoner_card', :locals => { :x => x }

rubygame/app/views/summoner/show.html.haml
%div{:class => "summoner-show-page"}
    -# change the background image of section
    - summonerInfo = @client.summoner.find(@summonerIGN)
    - ign = summonerInfo[:name]
    - icon = @client.summoner.icon(summonerInfo[:profileIconId])
    - level = summonerInfo[:summonerLevel]
    - rankInfo = @client.summoner.solo(@summonerIGN)
    - positions = @client.summoner.top_positions(@summonerIGN)
    - masteries = @client.summoner.champion_mastery(@summonerIGN, 3)
    - matches = @client.summoner.recent_matches(@summonerIGN)[:matches]
    - backgroundChampion = @client.champion.get_name(masteries[0][:championId])
    - if rankInfo != {}
        - tier = rankInfo[:tier]
        - rank = rankInfo[:rank]
        - lp = rankInfo[:leaguePoints]
        - win = rankInfo[:wins]
        - loss = rankInfo[:losses]
        - total = win + loss
        - win_rate = (win.to_f/total) * 100
        - ranks = @client.summoner.rank_info(@summonerIGN)
        
    - else
        - tier = 'UNRANKED'
        - rank = ''
        - lp = '-'
        - win = 0
        - loss = 0
        - total = win + loss
        - win_rate = (win.to_f/total) * 100


    %div{:class => "section--intro", :style => "background-image: url('http://ddragon.leagueoflegends.com/cdn/img/champion/splash/#{backgroundChampion}_0.jpg')"}
        %div{:class => "container--narrow--flex"}
            %div{:class => "group--icon"}
                - if tier != 'UNRANKED'
                    %img{:src => asset_path("ranks-borders/#{tier}.png")}/
                %div{:class => "icon", :style => "background-image: url('#{icon}')"}
                %p{:class => "level"} #{level}

            %div{:class => "group--info"}
                %p{:class => "name"} #{ign}
                %p{:class => "rank"} #{tier} #{rank}
                %p{:class => "lp"} #{lp} LP

            %div{:class => "group"}
                %div{:class => "rank-group"}
                    - unless ranks.nil?
                        - ranks.each do |r|
                            - t = r[:tier]
                            - rn = r[:rank]
                            -if r[:queueType].eql?'RANKED_SOLO_5x5'
                                - title = 'SOLO'
                            -elsif r[:queueType].eql?'RANKED_FLEX_SR'
                                - title = 'FLEX'
                            -elsif r[:queueType].eql?'RANKED_FLEX_TT'
                                -title = 'TT'
                            %div{:class => "individual"}
                                %p{:class => "title"} #{title}
                                %img{:src => asset_path("rank-icons/#{t}_#{rn}.png"), :class => "image"}/

                %div{:class => "position-group"}
                    - positions.each do |pos|
                        -position = pos
                        %div{:class => "individual"}
                            %p{:class => "title"} #{position}
                            %img{:src => asset_path("positions/#{position}.png"), :class => "image"}/

            - if @favorite
                = link_to summoner_favorites_delete_path(:ign => ign), :method => :delete, :class => "mdl-button mdl-js-button button--follow" do
                    %i{:class => 'material-icons md-light'} star
            - else
                = link_to summoner_favorites_save_path(:ign => ign), :method => :post, :class => "mdl-button mdl-js-button button--follow" do
                    %i{:class => 'material-icons'} star_outline

    %div{:class => "section--kda-champs"}
        %div{:class => "container--narrow--flex"}
            %div{:class => "group"}
                %div{:class => "win-loss"}
                    -# the width would be the count/total
                    %p{:class => "win-count", :style => "width: #{win_rate}%"} #{win}W
                    %p{:class => "loss-count", :style => "width: calc(100% - #{win_rate}%)"} #{loss}L
                %p{:class => "kda"} 3.7:2:5 KDA (37%)

            - masteries.each do |champ|
                - champIcon = @client.champion.icon(@client.champion.get_name(champ[:championId]))
                - points = @client.champion.points(champ[:championPoints])
                %div{:class => "group"}
                    %div{:class => "most-played-champion"}
                        %div{:class => "icon--smaller",:style => "background-image: url('#{champIcon}')"}
                        %p{:class => "win-loss-count"} #{points}

    %div{:class => "section--recent-games"}
        %div{:class => "container--narrow"}
            - (0...5).each do |x|
                = render :partial => 'partials/summoner_games', :locals => { :m => matches[x] }

rubygame/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rubygame/app/views/users/new.html.haml
%div{:class => "mdl-grid content-center"}
  %div{:class => "group"}
    = link_to "I have an account",auth_index_path, :class => "mdl-button mdl-js-button mdl-js-ripple-effect"
    %a{:class => "mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--colored"} I am a new user

  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message

    %div{:class => "mdl-textfield mdl-js-textfield"}
      = f.label :email, :class => "mdl-textfield__label"
      = f.text_field :email, :class => "mdl-textfield__input"

    %div{:class => "mdl-textfield mdl-js-textfield"}
      = f.label :password, :class => "mdl-textfield__label"
      = f.password_field :password, :class => "mdl-textfield__input"

    %div{:class => "mdl-textfield mdl-js-textfield"}
      = f.label :password_confirmation, :class => "mdl-textfield__label"
      = f.password_field :password_confirmation, :class => "mdl-textfield__input"

    %input{:class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", :type => "submit", :value => "Create account"}

%br
%br
%div{:class => "google_button"}
  - if current_user
    Signed in as
    = succeed "!" do
      %strong= current_user.name
    = link_to "Sign out", signout_path, id: "sign_out"
  - else
    = link_to image_tag('google_image.png'), "/auth/google_oauth2", id: "sign_in"

rubygame/app/views/users/show.haml
%p
  - if current_user
    Signed in as
    
    %strong= @user.name
    %p
      Provider:
      %strong=@user.provider
    %p
      UserID:
      %strong=@user.uid
      
    = link_to "Sign out", signout_path, id: "sign_out"
    
    

rubygame/app/views/users/show.html.haml
%div{:class => "user_info"}
  %p
    - if current_user
      Signed in as
      
      %strong= @user.name
      %p
        Provider:
        %strong=@user.provider
      %p
        UserID:
        %strong=@user.uid
      %p
        Email Address:
        %strong=@user.email
      
      
        
      = link_to "Sign out", signout_path, id: "sign_out"
    
    